name: 01-context
run-name: 06-context | DEBUG - ${{inputs.debug}}
on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default:  false
    

jobs:
  build:
    runs-on: ubuntu-latest
    environment: MY_ENV
    steps:
    - name: Display Event Information
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"
        echo "Actor ${{github.actor}}"
        echo "Workflow ${{github.workflow}}"
        echo "run_id ${{github.run_id}}"
        echo "run_number ${{github.run_number}}"
    - name: Retrieve Variables
      run: |
        echo "Variable value ${{vars.MY_VAR}}"    
        
